version: "3.9"

services:
  redis-master:
    image: redis:6.2.4
    container_name: redis-master
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      redis-network:
        aliases:
          - redis-master
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-slave:
    image: redis:6.2.4
    command: redis-server --appendonly yes --slaveof redis-master 6379
    volumes:
      - redis-slave-data:/data
    networks:
      redis-network:
        aliases:
          - redis-slave
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - "6380-6381:6379"

  redis-sentinel:
    image: redis:6.2.4
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-network:
        aliases:
          - redis-sentinel
    depends_on:
      - redis-master
      - redis-slave
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - "26379-26381:26379"

networks:
  redis-network:
    external: true

volumes:
  redis-master-data:
  redis-slave-data:
